# Generated by Django 4.0 on 2025-04-16 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=50)),
                ('part_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Part Number must be 6 to 10 alphanumeric characters.', regex='^[0-9A-Za-z]{6,10}$')])),
                ('size_mm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
